package al.vodafone.vodafone_project_backend.service;

import al.vodafone.vodafone_project_backend.model.Pack;
import al.vodafone.vodafone_project_backend.model.Tourist;
import al.vodafone.vodafone_project_backend.model.UserSubscription;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;

/**
 * Talks to PassKit (app.passkit.com) to issue and update Apple/Google Wallet
 * passes. PassKit holds its own Apple Pass Type ID and Google Wallet issuer
 * account, which is the whole point of using them — we never touch Apple
 * Developer or Google Play Console credentials ourselves.
 *
 * Auth: a Long-Lived API Token, generated from your PassKit program under
 * Settings -> Pass APIs. Keep it out of application.properties/version
 * control the same way you should for the Gmail app password already in
 * there — pass it in as an environment variable in real deployments.
 */
@Service
@Slf4j
public class PassKitService {

    private static final DateTimeFormatter EXPIRY_LABEL_FORMAT =
            DateTimeFormatter.ofPattern("d MMM yyyy", Locale.ENGLISH).withZone(ZoneOffset.UTC);

    private final RestClient restClient;
    private final String programId;
    private final String tierId;
    private final String passUrlHost;
    private final String frontendBaseUrl;

    public PassKitService(
            @Value("${passkit.api.base-url}") String apiBaseUrl,
            @Value("${passkit.api.token}") String apiToken,
            @Value("${passkit.program-id}") String programId,
            @Value("${passkit.tier-id}") String tierId,
            @Value("${passkit.pass-url-host}") String passUrlHost,
            @Value("${app.frontend.base-url}") String frontendBaseUrl
    ) {
        this.programId = programId;
        this.tierId = tierId;
        this.passUrlHost = passUrlHost;
        this.frontendBaseUrl = frontendBaseUrl;
        this.restClient = RestClient.builder()
                .baseUrl(apiBaseUrl)
                .defaultHeader("Authorization", "Bearer " + apiToken)
                .defaultHeader("Content-Type", "application/json")
                .build();
    }

    /**
     * Enrolls (or updates, since PassKit upserts by externalId) a tourist as
     * a member so their pack shows up as a Wallet pass. Best-effort: if
     * PassKit is unreachable or misconfigured this returns empty rather than
     * throwing, so a PassKit outage never blocks pack activation — same
     * philosophy as email sending elsewhere in this service layer.
     */
    public Optional<PassKitEnrollment> enrollTourist(Tourist tourist, UserSubscription subscription, Pack pack) {
        try {
            Map<String, Object> body = new LinkedHashMap<>();
            body.put("programId", programId);
            body.put("tierId", tierId);
            body.put("externalId", subscription.getId().toString());
            body.put("person", Map.of(
                    "displayName", tourist.getFirstName() + " " + tourist.getLastName(),
                    "forename", tourist.getFirstName(),
                    "surname", tourist.getLastName(),
                    "emailAddress", tourist.getEmail()
            ));

            // Custom pass fields — verified against the live PassKit account by
            // enrolling a real test member and inspecting the returned
            // pass.json (a .pkpass is just a zip). Confirmed there:
            //  - metaData is the correct top-level key, and its sub-keys become
            //    "meta.<key>" field keys in the pass template.
            //  - the pass's barcode is auto-generated by PassKit from the member
            //    ID (barcode.message = member id, format PKBarcodeFormatQR) —
            //    there is no per-enrollment barcode override in the Member API,
            //    so the frontend must never render its own fake QR for this;
            //    the wallet pass's built-in QR *is* the real one.
            //  - the pass DESIGN itself (field layout, positions, colors,
            //    back-of-card links) lives entirely in PassKit's visual Pass
            //    Designer — that surface isn't exposed by the public REST API
            //    this service talks to, only per-member *values* are. This
            //    method sends every value the design needs; binding a
            //    template field to one of these keys is a one-time step in
            //    the Designer (Settings -> Pass APIs program -> Designs).
            //
            //  "expires" is a fixed calendar date computed once at enrollment
            //  (now + pack duration), not a day-count that decrements over
            //  time — showing a live countdown would need a scheduled job
            //  that re-pushes updated metaData daily, which doesn't exist
            //  yet. A fixed expiry date needs no ongoing infrastructure and
            //  is exactly as informative.
            String expiresLabel = EXPIRY_LABEL_FORMAT.format(Instant.now().plusSeconds(pack.getDurationDays() * 86400L));

            body.put("metaData", Map.of(
                    "data", pack.getDataAllowance() != null ? pack.getDataAllowance() : "",
                    "minutes", String.valueOf(pack.getMinutesAllowance()),
                    "validDays", String.valueOf(pack.getDurationDays()),
                    "expires", expiresLabel,
                    "gameHubUrl", frontendBaseUrl + "/game-hub?touristId=" + tourist.getId(),
                    // Matches the "usageDashboardUrl" meta field you already created
                    // in the Designer (Label: "Data & Usage Check") — send under
                    // that exact key so it binds without needing a new field.
                    "usageDashboardUrl", frontendBaseUrl + "/my-pack?touristId=" + tourist.getId()
            ));

            // POST creates a new member; PUT only updates an existing one and
            // 404s otherwise (confirmed against the live API — this was the
            // actual bug silently breaking every enrollment, since the catch
            // block below swallows the failure).
            Map<?, ?> response = restClient.post()
                    .uri("/members/member")
                    .body(body)
                    .retrieve()
                    .body(Map.class);

            Object memberId = response != null ? response.get("id") : null;
            if (memberId == null) {
                log.warn("PassKit enrollment for subscription {} returned no member id — check response shape.",
                        subscription.getId());
                return Optional.empty();
            }

            String passUrl = passUrlHost + "/" + memberId;
            return Optional.of(new PassKitEnrollment(memberId.toString(), passUrl));

        } catch (Exception e) {
            log.error("PassKit enrollment failed for subscription {}: {}", subscription.getId(), e.getMessage(), e);
            return Optional.empty();
        }
    }

    public record PassKitEnrollment(String memberId, String passUrl) {
        public String applePassUrl() {
            return passUrl + ".pkpass";
        }

        public String googlePassUrl() {
            return passUrl + ".gpay";
        }
    }
}